version: "3.9"

# --------------------------------------------------
# تنظیمات مشترک سرویس‌های Django و Celery
# --------------------------------------------------
x-django-service: &django-service

  image: onlineshop-django:front

  build:
    context: .
    dockerfile: Dockerfile

  init: true

  restart: unless-stopped

  stop_signal: SIGTERM

  stop_grace_period: 30s

  env_file:
    - ./deployment/env/.env

  volumes:
    # دیتابیس SQLite روی سیستم Host نگهداری می‌شود.
    - ./onlineshop:/app

    # فایل‌های static
    - ./static_root:/static_root

    # فایل‌های media
    - ./media_root:/media_root

    # لاگ‌های Django
    - ./logs:/logs

  depends_on:
    redis:
      condition: service_healthy

  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

  networks:
    - backend


services:

  # --------------------------------------------------
  # Redis
  # --------------------------------------------------

  redis:

    image: redis:8-alpine

    container_name: onlineshop_front_redis

    restart: unless-stopped

    volumes:
      - redis_front_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    networks:
      - backend


  # --------------------------------------------------
  # Django Development Server
  # --------------------------------------------------

  django:

    <<: *django-service

    container_name: onlineshop_front_django

    command: >
      python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"


  # --------------------------------------------------
  # Celery Worker
  # --------------------------------------------------

  celery_worker:

    <<: *django-service

    container_name: onlineshop_front_celery_worker

    command: >
      celery
      -A onlineshop
      worker
      --loglevel=INFO


  # --------------------------------------------------
  # Celery Beat
  # --------------------------------------------------

  celery_beat:

    <<: *django-service

    container_name: onlineshop_front_celery_beat

    command: >
      celery
      -A onlineshop
      beat
      --loglevel=INFO
      --schedule=/tmp/celery/celerybeat-schedule

    tmpfs:
      - /tmp/celery


# --------------------------------------------------
# Volumes
# --------------------------------------------------

volumes:

  redis_front_data:


# --------------------------------------------------
# Network
# --------------------------------------------------

networks:

  backend:
    driver: bridge