services:

  postgres:
    image: postgres:17
    restart: unless-stopped

    env_file:
      - development/env/development.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: unless-stopped

    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - development/env/development.env

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
    driver: local