# Generated by Django 6.0.5 on 2026-06-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_rename_discounttarget_discountscope_and_more'),
        ('products', '0006_remove_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountscope',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='discountscope',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='products.category'),
        ),
        migrations.AlterField(
            model_name='discountscope',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='discounts.discount'),
        ),
        migrations.AlterField(
            model_name='discountscope',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='discountscope',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='discountscope',
            index=models.Index(fields=['product'], name='discounts_d_product_d7c103_idx'),
        ),
        migrations.AddIndex(
            model_name='discountscope',
            index=models.Index(fields=['variant'], name='discounts_d_variant_eff61c_idx'),
        ),
        migrations.AddIndex(
            model_name='discountscope',
            index=models.Index(fields=['category'], name='discounts_d_categor_c504cc_idx'),
        ),
        migrations.AddIndex(
            model_name='discountscope',
            index=models.Index(fields=['brand'], name='discounts_d_brand_i_885c7b_idx'),
        ),
    ]
