# Generated by Django 6.0.5 on 2026-06-11 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_productvariant_discount_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('processing', 'در حال آماده سازی'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('address_snapshot', models.JSONField(verbose_name='اسنپ شات آدرس')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='جمع کالاها')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ تخفیف')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه ارسال')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ نهایی')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='قیمت واحد')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='تخفیف واحد')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='قیمت نهایی واحد')),
                ('product_snapshot', models.JSONField(verbose_name='اسنپ شات محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'variant'), name='unique_variant_per_order'),
        ),
    ]
