# Generated by Django 6.0.5 on 2026-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method_snapshot',
            field=models.JSONField(default='{', verbose_name='اطلاعات روش ارسال'),
            preserve_default=False,
        ),
    ]
