# Generated by Django 6.0.5 on 2026-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='تصویر اصلی'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_product_image'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('variant',), name='unique_primary_variant_image'),
        ),
    ]
