# Generated by Django 6.0.5 on 2026-07-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='final_price',
            field=models.PositiveIntegerField(verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
