# Generated by Django 6.0.5 on 2026-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productvariant_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
