# Generated by Django 6.0.5 on 2026-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/', verbose_name='تصویر'),
        ),
    ]
