# Generated by Django 6.0.5 on 2026-08-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeValueProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='نام استاندارد ویژگی تکمیلی مانند color_code یا rgb', max_length=100, verbose_name='کلید')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='products.productattributevalue', verbose_name='مقدار ویژگی')),
            ],
            options={
                'verbose_name': 'خاصیت مقدار ویژگی',
                'verbose_name_plural': 'خاصیت\u200cهای مقدار ویژگی',
                'indexes': [models.Index(fields=['key', 'value'], name='products_pr_key_7856b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('attribute_value', 'key'), name='unique_attribute_value_property_key')],
            },
        ),
    ]
