# Generated by Django 6.0.5 on 2026-08-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productattributevalueproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantAttributeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='نام استاندارد ویژگی تکمیلی مانند color_code یا rgb', max_length=100, verbose_name='کلید')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'خاصیت ویژگی تنوع',
                'verbose_name_plural': 'خاصیت\u200cهای ویژگی تنوع',
            },
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'مقدار ویژگی محصول', 'verbose_name_plural': 'مقادیر ویژگی محصول'},
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantattribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_filterable',
            field=models.BooleanField(default=False, verbose_name='قابل استفاده در فیلتر'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='is_highlight',
            field=models.BooleanField(default=False, verbose_name='نمایش به عنوان ویژگی شاخص'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='products.productattribute', verbose_name='ویژگی'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='value',
            field=models.CharField(max_length=255, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='products.productattribute', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvariantattribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.productvariant', verbose_name='تنوع محصول'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute', 'value'), name='unique_product_attribute_value'),
        ),
        migrations.AddConstraint(
            model_name='productvariantattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute'), name='unique_variant_attribute'),
        ),
        migrations.AddField(
            model_name='productvariantattributeproperty',
            name='variant_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='products.productvariantattribute', verbose_name='ویژگی تنوع'),
        ),
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='attribute_value',
        ),
        migrations.AddIndex(
            model_name='productvariantattributeproperty',
            index=models.Index(fields=['key', 'value'], name='products_pr_key_c49434_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariantattributeproperty',
            constraint=models.UniqueConstraint(fields=('variant_attribute', 'key'), name='unique_variant_attribute_property_key'),
        ),
    ]
