# Generated by Django 6.0.5 on 2026-08-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productvariantattributeproperty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='products.productattribute', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='productvariantattribute',
            name='value',
            field=models.CharField(max_length=255, verbose_name='مقدار'),
        ),
    ]
