# Generated by Django 6.0.5 on 2026-06-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'Zarinpal')], db_index=True, max_length=20, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='کد Authority')),
                ('ref_id', models.CharField(blank=True, max_length=255, verbose_name='شماره مرجع پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('failure_reason', models.TextField(blank=True, verbose_name='دلیل خطا')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payment_status_idx'), models.Index(fields=['created_at'], name='payment_created_idx'), models.Index(fields=['gateway'], name='payment_gateway_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='unique_success_payment_per_order')],
            },
        ),
    ]
