# Generated by Django 6.0.5 on 2026-07-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('section_type', models.CharField(choices=[('hero_slider', 'اسلایدر اصلی'), ('banner', 'بنر'), ('categories', 'دسته\u200cبندی\u200cها'), ('featured_products', 'محصولات ویژه'), ('latest_products', 'جدیدترین محصولات'), ('best_seller_products', 'پرفروش\u200cترین محصولات'), ('discount_products', 'محصولات تخفیف\u200cدار'), ('brands', 'برندها'), ('custom_products', 'محصولات انتخابی')], db_index=True, max_length=50, verbose_name='نوع سکشن')),
                ('layout', models.CharField(choices=[('grid', 'شبکه\u200cای'), ('slider', 'اسلایدر'), ('carousel', 'کاروسل'), ('banner', 'بنر')], max_length=30, verbose_name='نوع نمایش')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سکشن صفحه اصلی',
                'verbose_name_plural': 'سکشن\u200cهای صفحه اصلی',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='زیرعنوان')),
                ('desktop_image', models.ImageField(upload_to='home/hero/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(blank=True, upload_to='home/hero/', verbose_name='تصویر موبایل')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه')),
                ('button_url', models.CharField(blank=True, max_length=500, verbose_name='آدرس دکمه')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='home.homesection', verbose_name='سکشن')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('desktop_image', models.ImageField(upload_to='home/banner/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(blank=True, upload_to='home/banner/', verbose_name='تصویر موبایل')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='home.homesection', verbose_name='سکشن')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HomeSectionBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='ترتیب نمایش')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.brand', verbose_name='برند')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homesection', verbose_name='سکشن')),
            ],
            options={
                'verbose_name': 'برند سکشن',
                'verbose_name_plural': 'برندهای سکشن',
                'ordering': ('order',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('section', 'brand'), name='unique_home_section_brand')],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.category', verbose_name='دسته\u200cبندی')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homesection', verbose_name='سکشن')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی سکشن',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای سکشن',
                'ordering': ('order',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('section', 'category'), name='unique_home_section_category')],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product', verbose_name='محصول')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homesection', verbose_name='سکشن')),
            ],
            options={
                'verbose_name': 'محصول سکشن',
                'verbose_name_plural': 'محصولات سکشن',
                'ordering': ('order',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('section', 'product'), name='unique_home_section_product')],
            },
        ),
    ]
