# Generated by Django 6.0.5 on 2026-06-11 21:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='مقدار تخفیف')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(verbose_name='شروع')),
                ('end_date', models.DateTimeField(verbose_name='پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DiscountTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.PositiveSmallIntegerField(choices=[(1, 'برند'), (2, 'دسته بندی'), (3, 'محصول'), (4, 'محصول انتخوابی')])),
            ],
            options={
                'verbose_name': 'هدف تخفیف',
                'verbose_name_plural': 'اهداف تخفیف',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.coupon')),
            ],
        ),
    ]
