# Generated by Django 6.0.5 on 2026-06-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
        ('products', '0006_remove_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountTarget',
            new_name='DiscountScope',
        ),
        migrations.RenameIndex(
            model_name='discountscope',
            new_name='discounts_d_discoun_f37f1e_idx',
            old_name='discounts_d_discoun_3ed691_idx',
        ),
    ]
