# Generated by Django 6.0.5 on 2026-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_discountscope_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
    ]
