# Generated by Django 6.0.5 on 2026-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_alter_discount_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
    ]
