# Generated by Django 6.0.5 on 2026-06-17 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روش ارسال')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد روش ارسال')),
                ('price', models.PositiveIntegerField(verbose_name='هزینه ارسال')),
                ('estimated_days', models.PositiveSmallIntegerField(verbose_name='زمان تقریبی تحویل (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار آماده\u200cسازی'), ('PACKAGED', 'بسته\u200cبندی شده'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل شده'), ('RETURNED', 'مرجوع شده'), ('CANCELED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order', verbose_name='سفارش')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingmethod', verbose_name='روش ارسال')),
            ],
            options={
                'verbose_name': 'مرسوله',
                'verbose_name_plural': 'مرسوله\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
