# Generated by Django 6.0.5 on 2026-07-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_discountscope_brand_and_more'),
        ('orders', '0004_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.coupon', verbose_name='کوپن'),
        ),
    ]
