# Generated by Django 6.0.5 on 2026-06-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('product', 'attribute', 'value')},
        ),
    ]
