# Generated by Django 6.0.5 on 2026-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productattributevalue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
    ]
