# Generated by Django 6.0.5 on 2026-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
