# Generated by Django 6.0.5 on 2026-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='معتبر'),
        ),
    ]
